# Generated by Django 4.1.4 on 2022-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
