# Generated by Django 4.1.4 on 2022-12-19 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reader',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
