# Generated by Django 4.1.4 on 2022-12-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_document_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
